# Generated by Django 4.1 on 2024-05-20 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AddresseEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("addresse", models.EmailField(max_length=254, unique=True)),
                ("estinterne", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("subject", models.CharField(default=None, max_length=200)),
                ("content", models.TextField(default="")),
                (
                    "sender_mail",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_email",
                        to="investigation.addresseemail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Groupe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_groupe", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReceiversMail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("To", "To"), ("Cc", "Cc"), ("Bcc", "Bcc")],
                        max_length=3,
                    ),
                ),
                (
                    "addresse_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipient_email",
                        to="investigation.addresseemail",
                    ),
                ),
                ("email", models.ManyToManyField(to="investigation.email")),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lastname", models.CharField(max_length=50)),
                ("firstname", models.CharField(max_length=50)),
                ("mailbox", models.CharField(max_length=50)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investigation.groupe",
                    ),
                ),
            ],
            options={
                "unique_together": {("firstname", "lastname")},
            },
        ),
        migrations.CreateModel(
            name="CoupleCommunication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_addresse_1", models.EmailField(max_length=100)),
                ("employee_addresse_2", models.EmailField(max_length=100)),
                ("total_mails_echanges", models.IntegerField()),
            ],
            options={
                "unique_together": {("employee_addresse_1", "employee_addresse_2")},
            },
        ),
        migrations.AddField(
            model_name="addresseemail",
            name="employee",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="investigation.employee",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="addresseemail",
            unique_together={("addresse", "employee")},
        ),
    ]
