# Generated by Django 4.1 on 2024-04-24 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AddresseEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("addresse", models.EmailField(max_length=254, unique=True)),
                ("estInterne", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("subject", models.CharField(default=None, max_length=200)),
                ("content", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="ReceiversMail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("To", "To"), ("Cc", "Cc"), ("Bcc", "Bcc")],
                        max_length=3,
                    ),
                ),
                (
                    "addresse_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investigation.addresseemail",
                    ),
                ),
                ("email", models.ManyToManyField(to="investigation.email")),
                (
                    "receivers",
                    models.ManyToManyField(
                        related_name="email", to="investigation.email"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lastname", models.CharField(max_length=50)),
                ("firstname", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50, null=True)),
                ("mailbox", models.CharField(max_length=50)),
            ],
            options={
                "unique_together": {("firstname", "lastname")},
            },
        ),
        migrations.AddField(
            model_name="email",
            name="receivers",
            field=models.ManyToManyField(
                related_name="receivers_emails", to="investigation.receiversmail"
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="sender_mail",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_email",
                to="investigation.addresseemail",
            ),
        ),
        migrations.AddField(
            model_name="addresseemail",
            name="employee",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="investigation.employee",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="addresseemail",
            unique_together={("addresse", "employee")},
        ),
    ]
