# Generated by Django 4.1 on 2024-05-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="email",
            name="subject",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
