# Generated by Django 4.1 on 2024-04-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="email",
            name="receivers",
        ),
        migrations.RemoveField(
            model_name="receiversmail",
            name="receivers",
        ),
    ]
