# Generated by Django 4.1 on 2024-03-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together={("firstname", "lastname")},
        ),
    ]
