# Generated by Django 4.1 on 2024-04-25 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0002_remove_email_receivers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiversmail",
            name="addresse_email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipient_email",
                to="investigation.addresseemail",
            ),
        ),
    ]
