# Generated by Django 4.1 on 2024-03-15 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0002_alter_employee_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddresseEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("addresse", models.EmailField(max_length=254, unique=True)),
                ("estInterne", models.BooleanField(default=None)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investigation.employee",
                    ),
                ),
            ],
            options={
                "unique_together": {("addresse", "employee")},
            },
        ),
    ]
