# Generated by Django 4.1 on 2024-05-22 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0003_alter_email_content_alter_employee_category"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="couplecommunication",
            unique_together={
                ("employee_addresse_1", "employee_addresse_2", "total_mails_echanges")
            },
        ),
    ]
