# Generated by Django 4.1 on 2024-03-15 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0003_addresseemail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_id", models.CharField(max_length=200, unique=True)),
                ("dateSend", models.DateTimeField()),
                (
                    "receiver_addresses",
                    models.ManyToManyField(
                        related_name="rec_emails", to="investigation.addresseemail"
                    ),
                ),
                (
                    "sender_mail",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_email",
                        to="investigation.addresseemail",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="addresseemail",
            name="email",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender_email",
                to="investigation.email",
            ),
        ),
        migrations.AddField(
            model_name="addresseemail",
            name="receiver_emails",
            field=models.ManyToManyField(
                related_name="rec_addresses", to="investigation.email"
            ),
        ),
    ]
