# Generated by Django 4.1 on 2024-04-26 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0003_alter_receiversmail_addresse_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="addresseemail",
            old_name="estInterne",
            new_name="estinterne",
        ),
    ]
