# Generated by Django 4.1 on 2024-05-14 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0004_rename_estinterne_addresseemail_estinterne"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoupleCommunication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_addresse_1", models.EmailField(max_length=100)),
                ("employee_addresse_2", models.EmailField(max_length=100)),
                ("total_mails_echanges", models.IntegerField()),
            ],
            options={
                "unique_together": {
                    (
                        "employee_addresse_1",
                        "employee_addresse_2",
                        "total_mails_echanges",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="ContenuEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenu", models.TextField(default="")),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investigation.email",
                    ),
                ),
            ],
        ),
    ]
