# Generated by Django 4.1 on 2024-03-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0004_email_addresseemail_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="email_id",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
