# Generated by Django 4.1 on 2024-05-03 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0005_couplecommunication"),
    ]

    operations = [
        migrations.RenameField(
            model_name="couplecommunication",
            old_name="employee_id_1",
            new_name="employee_addresse_1",
        ),
        migrations.RenameField(
            model_name="couplecommunication",
            old_name="employee_id_2",
            new_name="employee_addresse_2",
        ),
        migrations.AlterUniqueTogether(
            name="couplecommunication",
            unique_together={
                ("employee_addresse_1", "employee_addresse_2", "total_mails_echanges")
            },
        ),
    ]
