# Generated by Django 4.1 on 2024-05-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0005_couplecommunication_contenuemail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contenuemail",
            name="contenu",
        ),
    ]
