# Generated by Django 4.1 on 2024-03-15 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0006_alter_email_email_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addresseemail",
            name="email",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender_email",
                to="investigation.email",
            ),
        ),
        migrations.AlterField(
            model_name="addresseemail",
            name="receiver_emails",
            field=models.ManyToManyField(
                related_name="receive_addresses", to="investigation.email"
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="email_id",
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="email",
            name="receiver_addresses",
            field=models.ManyToManyField(
                related_name="receive_emails", to="investigation.addresseemail"
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="sender_mail",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_email",
                to="investigation.addresseemail",
            ),
        ),
    ]
