# Generated by Django 4.1 on 2024-05-17 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0006_remove_contenuemail_contenu"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContenuEmail",
        ),
    ]
