# Generated by Django 4.1 on 2024-03-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0007_alter_addresseemail_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="contenu",
            field=models.TextField(default=" "),
        ),
        migrations.AddField(
            model_name="email",
            name="subject",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
