# Generated by Django 4.1 on 2024-03-16 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0008_email_contenu_email_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="email",
            name="receiver_addresses",
        ),
        migrations.AlterField(
            model_name="email",
            name="contenu",
            field=models.TextField(default=""),
        ),
        migrations.CreateModel(
            name="ReceiversMail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("TO", "To"), ("CC", "Cc"), ("BCC", "Bcc")],
                        max_length=3,
                    ),
                ),
                (
                    "addresse_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investigation.addresseemail",
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investigation.email",
                    ),
                ),
            ],
        ),
    ]
