# Generated by Django 4.1 on 2024-03-16 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "investigation",
            "0009_remove_email_receiver_addresses_alter_email_contenu_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="addresseemail",
            name="email",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sender_email",
                to="investigation.email",
            ),
        ),
        migrations.AlterField(
            model_name="addresseemail",
            name="estInterne",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="email",
            name="sender_mail",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_email",
                to="investigation.addresseemail",
            ),
        ),
    ]
