# Generated by Django 4.1 on 2024-03-16 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0010_alter_addresseemail_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addresseemail",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="investigation.employee",
            ),
        ),
    ]
