# Generated by Django 4.1 on 2024-03-16 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0011_alter_addresseemail_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="email",
            name="email_id",
        ),
    ]
