# Generated by Django 4.1 on 2024-03-17 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0013_alter_addresseemail_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addresseemail",
            name="email",
        ),
        migrations.AddField(
            model_name="email",
            name="receivers",
            field=models.ManyToManyField(
                related_name="received_emails",
                through="investigation.ReceiversMail",
                to="investigation.addresseemail",
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="sender_mail",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_email",
                to="investigation.addresseemail",
            ),
        ),
    ]
