# Generated by Django 4.1 on 2024-03-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0014_remove_addresseemail_email_email_receivers_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="receiversmail",
            unique_together={("email", "addresse_email")},
        ),
    ]
