# Generated by Django 4.1 on 2024-03-23 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0016_alter_email_datesend"),
    ]

    operations = [
        migrations.RenameField(
            model_name="email",
            old_name="dateSend",
            new_name="date",
        ),
    ]
