# Generated by Django 4.1 on 2024-04-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0017_rename_datesend_email_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiversmail",
            name="type",
            field=models.CharField(
                choices=[("To", "To"), ("Cc", "Cc"), ("Bcc", "Bcc")], max_length=3
            ),
        ),
    ]
