# Generated by Django 4.0.10 on 2024-03-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0017_rename_datesend_email_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
