# Generated by Django 4.1 on 2024-04-07 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0018_alter_receiversmail_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="receiversmail",
            unique_together=set(),
        ),
    ]
