# Generated by Django 4.1 on 2024-04-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0019_alter_receiversmail_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="receiversmail",
            unique_together={("email", "addresse_email")},
        ),
    ]
