# Generated by Django 4.1 on 2024-04-11 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0022_rename_contenu_email_content"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="email",
            unique_together={("date", "sender_mail", "subject", "content")},
        ),
    ]
