# Generated by Django 4.1 on 2024-04-11 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0023_alter_email_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="email",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="receiversmail",
            unique_together={("email", "addresse_email")},
        ),
    ]
