# Generated by Django 4.1 on 2024-04-11 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0024_alter_email_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="receiversmail",
            unique_together={("email", "addresse_email", "type")},
        ),
    ]
