# Generated by Django 4.1 on 2024-04-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0026_alter_email_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
