# Generated by Django 4.1 on 2024-04-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0029_alter_receiversmail_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="receiversmail",
            unique_together=set(),
        ),
    ]
